class_name RaidRegionCatalog
extends RefCounted

const DEFAULT_ZONE_ID := "jongno_outskirts"

const COMMON_BUILDINGS := [
	"hanbit_apartment_8x4",
	"academy_tower_6x4",
	"gangnam_single_story_8x4_aligned",
	"gangnam_ruined_lowrise_6x8_aligned",
	"gangnam_glass_tower_6x4_aligned",
	"gangnam_lowrise_commercial_8x4_aligned",
	"gangnam_lowrise_garage_8x4_aligned",
	"gangnam_clinic_pharmacy_6x4_aligned",
	"gangnam_food_alley_4x6_aligned",
	"gangnam_damaged_officetel_6x6_aligned",
	"seoul_market_row_8x4_v1",
	"seoul_multifamily_villa_6x6_v1",
	"gangnam_luxury_showroom_6x6_v1",
	"seoul_laundromat_repair_8x4_v1",
	"seoul_redbrick_corner_villa_6x6_v1",
]

const PROFILES := {
	"jongno_outskirts": {
		"display_name": "종로 외곽",
		"identity": "넓은 간선도로와 생활권 폐허가 섞인 초반 탐색 구역",
		"ground_texture_path": "res://assets/tiles/asphalt.png",
		"asphalt_tint": Color("#ffffff"),
		"lot_tint": Color("#77756f"),
		"sidewalk_tint": Color("#aaa79e"),
		"marking_tint": Color("#d1c87d"),
		"outer_tint": Color(0.62, 0.66, 0.66, 1.0),
		"river_enabled": true,
		"vertical_road_bands": [Vector2i(2, 2), Vector2i(5, 6), Vector2i(9, 10), Vector2i(14, 15), Vector2i(20, 20)],
		"horizontal_road_bands": [Vector2i(2, 2), Vector2i(5, 6), Vector2i(9, 10), Vector2i(14, 15), Vector2i(20, 20)],
		"building_chance_multiplier": 1.0,
		"parking_chance": 0.58,
		"vehicle_chance": 0.46,
		"cover_chance": 0.68,
		"cover_style": "mixed",
		"street_prop_count": 14,
		"street_prop_chance": 0.14,
		"market_prop_chance": 0.42,
		"large_vehicle_pool": [
			"sedan", "sedan", "suv", "taxi", "delivery_van",
			"burned_sedan", "overturned_hatchback", "truck", "bus",
		],
		"parked_vehicle_pool": [
			"sedan", "suv", "taxi", "delivery_van", "intact_hatchback",
			"intact_hatchback", "burned_sedan",
		],
		"container_adjustments": {},
		"loot_focus": "통조림 · 보통탄 · 기본 부품",
		"tactical_rule": "큰 도로는 빠르지만 노출되고, 생활 골목은 안전합니다.",
		"district_radius": 2,
		"district_min_separation": 6,
		"playground_count": 2,
		"subway_count": 2,
		"apartment_estate_enabled": true,
		"allowed_buildings": COMMON_BUILDINGS,
		"entry_safe_radius": 30.0,
		"first_supply_distance": Vector2(8.0, 14.0),
		"mission_radius": 25.0,
		"recommended_duration_minutes": 24,
		"target_enemy_count": 24,
		"risk_split": Vector2(0.34, 0.70),
	},
	"namdaemun_market": {
		"display_name": "남대문 폐시장",
		"identity": "촘촘한 시장 골목, 짧은 시야, 식량과 공구 중심의 근거리 탐색",
		"ground_texture_path": "res://assets/tiles/regions/namdaemun_market_ground_v1.png",
		"asphalt_tint": Color("#ddd5c2"),
		"lot_tint": Color("#a59d88"),
		"sidewalk_tint": Color("#b8ad94"),
		"marking_tint": Color("#c7b76d"),
		"outer_tint": Color("#6f685b"),
		"river_enabled": false,
		"vertical_road_bands": [Vector2i(2, 2), Vector2i(5, 5), Vector2i(8, 9), Vector2i(12, 12), Vector2i(16, 16), Vector2i(20, 20)],
		"horizontal_road_bands": [Vector2i(2, 2), Vector2i(5, 5), Vector2i(8, 8), Vector2i(11, 12), Vector2i(15, 15), Vector2i(19, 20)],
		"building_chance_multiplier": 1.18,
		"parking_chance": 0.34,
		"vehicle_chance": 0.28,
		"cover_chance": 0.82,
		"cover_style": "mixed",
		"street_prop_count": 24,
		"street_prop_chance": 0.28,
		"market_prop_chance": 0.72,
		"large_vehicle_pool": [
			"delivery_van", "delivery_van", "delivery_van", "taxi", "taxi",
			"sedan", "intact_hatchback", "truck",
		],
		"parked_vehicle_pool": [
			"delivery_van", "delivery_van", "taxi", "sedan", "intact_hatchback",
		],
		"container_adjustments": {
			"street_cache": 2,
			"clothing_cache": 2,
			"ammo_case": -2,
			"toolbox": -2,
		},
		"loot_focus": "통조림 · 의류 · 생활 공구",
		"tactical_rule": "골목 시야가 짧고 엄폐물이 많아 근거리 우회가 유리합니다.",
		"district_radius": 3,
		"district_min_separation": 5,
		"playground_count": 1,
		"subway_count": 2,
		"apartment_estate_enabled": false,
		"allowed_buildings": [
			"gangnam_single_story_8x4_aligned", "gangnam_ruined_lowrise_6x8_aligned",
			"gangnam_lowrise_commercial_8x4_aligned", "gangnam_food_alley_4x6_aligned",
			"seoul_market_row_8x4_v1", "seoul_laundromat_repair_8x4_v1",
			"seoul_multifamily_villa_6x6_v1", "gangnam_luxury_showroom_6x6_v1",
			"seoul_redbrick_corner_villa_6x6_v1", "namdaemun_covered_market_8x4_v1",
		],
		"signature_building_id": "namdaemun_covered_market_8x4_v1",
		"signature_district": "market_lane",
		"entry_safe_radius": 34.0,
		"first_supply_distance": Vector2(9.0, 16.0),
		"mission_radius": 29.0,
		"recommended_duration_minutes": 26,
		"target_enemy_count": 30,
		"risk_split": Vector2(0.30, 0.66),
	},
	"euljiro_depths": {
		"display_name": "을지로 지하구역",
		"identity": "금속 공방과 산업 통로가 직선으로 이어지는 어두운 부품 파밍 구역",
		"ground_texture_path": "res://assets/tiles/regions/euljiro_industrial_ground_v1.png",
		"asphalt_tint": Color("#b9c2bd"),
		"lot_tint": Color("#77827f"),
		"sidewalk_tint": Color("#939c97"),
		"marking_tint": Color("#b8aa67"),
		"outer_tint": Color("#505b59"),
		"river_enabled": false,
		"vertical_road_bands": [Vector2i(2, 2), Vector2i(6, 6), Vector2i(10, 10), Vector2i(14, 14), Vector2i(19, 20)],
		"horizontal_road_bands": [Vector2i(2, 2), Vector2i(6, 6), Vector2i(10, 10), Vector2i(15, 15), Vector2i(20, 20)],
		"building_chance_multiplier": 1.08,
		"parking_chance": 0.42,
		"vehicle_chance": 0.36,
		"cover_chance": 0.76,
		"cover_style": "rubble",
		"street_prop_count": 20,
		"street_prop_chance": 0.22,
		"market_prop_chance": 0.34,
		"large_vehicle_pool": [
			"truck", "truck", "delivery_van", "delivery_van", "burned_sedan",
			"sedan", "overturned_hatchback",
		],
		"parked_vehicle_pool": [
			"delivery_van", "delivery_van", "truck", "sedan", "burned_sedan",
		],
		"container_adjustments": {
			"toolbox": 4,
			"ammo_case": 2,
			"street_cache": -4,
			"clothing_cache": -2,
		},
		"loot_focus": "총기 부품 · 공구 · 중급 탄약",
		"tactical_rule": "직선 산업 통로의 긴 사선과 지하 진입로를 번갈아 사용합니다.",
		"district_radius": 2,
		"district_min_separation": 6,
		"playground_count": 0,
		"subway_count": 3,
		"apartment_estate_enabled": false,
		"allowed_buildings": [
			"gangnam_ruined_lowrise_6x8_aligned", "gangnam_lowrise_garage_8x4_aligned",
			"gangnam_damaged_officetel_6x6_aligned", "seoul_laundromat_repair_8x4_v1",
			"gangnam_lowrise_commercial_8x4_aligned", "academy_tower_6x4",
			"seoul_market_row_8x4_v1", "seoul_multifamily_villa_6x6_v1",
			"gangnam_luxury_showroom_6x6_v1", "euljiro_metalworks_8x4_v1",
		],
		"signature_building_id": "euljiro_metalworks_8x4_v1",
		"signature_district": "market_lane",
		"entry_safe_radius": 36.0,
		"first_supply_distance": Vector2(10.0, 18.0),
		"mission_radius": 32.0,
		"recommended_duration_minutes": 27,
		"target_enemy_count": 37,
		"risk_split": Vector2(0.27, 0.62),
	},
	"yongsan_blockade": {
		"display_name": "용산 봉쇄선",
		"identity": "넓은 사선과 군용 엄폐물이 교차하는 장거리 교전 구역",
		"ground_texture_path": "res://assets/tiles/regions/yongsan_blockade_ground_v1.png",
		"asphalt_tint": Color("#d2d0c5"),
		"lot_tint": Color("#777a78"),
		"sidewalk_tint": Color("#9a9991"),
		"marking_tint": Color("#d5b45d"),
		"outer_tint": Color("#5b5f5d"),
		"river_enabled": false,
		"vertical_road_bands": [Vector2i(2, 2), Vector2i(8, 8), Vector2i(14, 14), Vector2i(20, 20)],
		"horizontal_road_bands": [Vector2i(2, 2), Vector2i(7, 7), Vector2i(13, 13), Vector2i(20, 20)],
		"building_chance_multiplier": 0.84,
		"parking_chance": 0.72,
		"vehicle_chance": 0.68,
		"cover_chance": 0.86,
		"cover_style": "barricade",
		"street_prop_count": 18,
		"street_prop_chance": 0.18,
		"market_prop_chance": 0.24,
		"large_vehicle_pool": [
			"truck", "truck", "truck", "bus", "bus", "burned_sedan",
			"overturned_hatchback", "suv",
		],
		"parked_vehicle_pool": [
			"truck", "delivery_van", "suv", "burned_sedan", "overturned_hatchback",
		],
		"container_adjustments": {
			"ammo_case": 3,
			"weapon_case": 1,
			"street_cache": -3,
			"clothing_cache": -1,
		},
		"loot_focus": "방어구 · 군용 탄약 · 무기 부품",
		"tactical_rule": "차량과 검문소를 옮겨 다니며 장거리 사선을 끊어야 합니다.",
		"district_radius": 2,
		"district_min_separation": 7,
		"playground_count": 0,
		"subway_count": 1,
		"apartment_estate_enabled": false,
		"allowed_buildings": [
			"gangnam_glass_tower_6x4_aligned", "gangnam_damaged_officetel_6x6_aligned",
			"gangnam_lowrise_garage_8x4_aligned", "gangnam_ruined_lowrise_6x8_aligned",
			"academy_tower_6x4", "hanbit_apartment_8x4",
			"seoul_market_row_8x4_v1", "seoul_multifamily_villa_6x6_v1",
			"gangnam_luxury_showroom_6x6_v1", "yongsan_checkpoint_depot_8x4_v1",
		],
		"signature_building_id": "yongsan_checkpoint_depot_8x4_v1",
		"signature_district": "luxury_core",
		"entry_safe_radius": 40.0,
		"first_supply_distance": Vector2(11.0, 20.0),
		"mission_radius": 36.0,
		"recommended_duration_minutes": 28,
		"target_enemy_count": 45,
		"risk_split": Vector2(0.25, 0.58),
	},
	"namsan_core": {
		"display_name": "남산 오염 핵심부",
		"identity": "붕괴한 고지대와 오염 공터 사이를 건너는 최고위험 심야 구역",
		"ground_texture_path": "res://assets/tiles/regions/namsan_contaminated_ground_v1.png",
		"asphalt_tint": Color("#aeb8a1"),
		"lot_tint": Color("#687061"),
		"sidewalk_tint": Color("#858d7b"),
		"marking_tint": Color("#b3a25b"),
		"outer_tint": Color("#454c43"),
		"river_enabled": false,
		"vertical_road_bands": [Vector2i(2, 2), Vector2i(7, 8), Vector2i(13, 14), Vector2i(20, 20)],
		"horizontal_road_bands": [Vector2i(2, 2), Vector2i(6, 6), Vector2i(11, 12), Vector2i(16, 16), Vector2i(20, 20)],
		"building_chance_multiplier": 0.72,
		"parking_chance": 0.48,
		"vehicle_chance": 0.58,
		"cover_chance": 0.90,
		"cover_style": "rubble",
		"street_prop_count": 22,
		"street_prop_chance": 0.24,
		"market_prop_chance": 0.18,
		"large_vehicle_pool": [
			"burned_sedan", "burned_sedan", "burned_sedan", "overturned_hatchback",
			"overturned_hatchback", "truck", "bus",
		],
		"parked_vehicle_pool": [
			"burned_sedan", "burned_sedan", "overturned_hatchback", "sedan",
		],
		"container_adjustments": {
			"secure_cache": 3,
			"weapon_case": 1,
			"ammo_case": 2,
			"street_cache": -4,
			"clothing_cache": -2,
		},
		"loot_focus": "청사진 · AP탄 · 최고급 장비",
		"tactical_rule": "개활지를 짧게 건너고 붕괴 잔해 뒤에서 다음 이동을 준비해야 합니다.",
		"district_radius": 2,
		"district_min_separation": 7,
		"playground_count": 0,
		"subway_count": 1,
		"apartment_estate_enabled": false,
		"allowed_buildings": [
			"gangnam_ruined_lowrise_6x8_aligned", "gangnam_damaged_officetel_6x6_aligned",
			"gangnam_glass_tower_6x4_aligned", "hanbit_apartment_8x4",
			"seoul_market_row_8x4_v1", "seoul_multifamily_villa_6x6_v1",
			"gangnam_luxury_showroom_6x6_v1", "seoul_redbrick_corner_villa_6x6_v1",
			"namsan_decon_station_8x4_v1",
		],
		"signature_building_id": "namsan_decon_station_8x4_v1",
		"signature_district": "luxury_core",
		"entry_safe_radius": 42.0,
		"first_supply_distance": Vector2(12.0, 22.0),
		"mission_radius": 40.0,
		"recommended_duration_minutes": 30,
		"target_enemy_count": 52,
		"risk_split": Vector2(0.22, 0.54),
	},
}


static func get_profile(zone_id: String) -> Dictionary:
	var resolved_id := zone_id if PROFILES.has(zone_id) else DEFAULT_ZONE_ID
	var profile := (PROFILES[resolved_id] as Dictionary).duplicate(true)
	profile["zone_id"] = resolved_id
	return profile


static func get_zone_ids() -> Array[String]:
	var result: Array[String] = []
	for zone_id in PROFILES.keys():
		result.append(str(zone_id))
	return result
